# Genetic algorithm constants / parameters
NUM_ELITES = 2
RANDOMS_PER_GENERATION = 2
TOURNAMENT_SIZE = 3
MUTATION_RATE = 0.1
MUTATION_STRENGTH = 0.5
INITIAL_WEIGHT_RANGE = (-0.05, 0.05)

# Fitness scoring
STUCK_FRAME_THRESHOLD = 90
STUCK_FRAME_PENALTY = 0.25
TIME_PENALTY_PER_FRAME = 0.05
GAME_SCORE_WEIGHT = 0.02
COIN_BONUS = 5
LEVEL_COMPLETION_BONUS = 10000
STUCK_BREAK_PENALTY = 50
DEATH_PENALTY = 100
BACKWARD_PENALTY = 0.3

# How many models get saved at the end of train.py
MAX_BEST_MODELS = 3